#!/bin/bash
# build-world-with-clang [cave-resolve args]
# build all packages on system with clang, except packages
# listed in a packages.gcc file, or ones compiled with clang already
#
# Copyright 2015 Kylie McClain <somasis@exherbo.org>
# Distributed under the terms of the ISC License
#

set -euf -o pipefail

packages_gcc="${packages_gcc:-$HOME/git/exheres/etc/clang-compat/packages.gcc}"
if [[ ! -f "$packages_gcc" ]];then
    packages_gcc="/var/db/paludis/repositories/somasis/etc/clang-compat/packages.gcc"
fi

printf "Building entire world with \`clang\`...\n"
printf "Note: packages listed in \"$packages_gcc\" will be excluded\n\n"

cave resolve "$@" -1x $(built-with gcc | cut -d' ' -f1 | grep -v -x -f "$packages_gcc")
