#!/bin/bash
# built-with [CC]
# shows what compiler was used for packages installed on a Paludis-using system
#
# Copyright 2015 Kylie McClain <somasis@exherbo.org>
# Distributed under the terms of the ISC License
#

set -eu -o pipefail
shopt -s failglob

pkgs=/var/db/paludis/repositories/installed/data/*/*

for pkg in $pkgs;do
    printf "%s:%s %s\n" \
        $(printf "$pkg" | sed 's#.*/data/##;s#/.*##;s#---#/#') \
        $(<"$pkg/SLOT") \
        $(printf $(<"$pkg/CC") | sed 's#.*-##g;s#.*/##g')
done | {
    if [[ "$#" -gt 0 ]];then
        grep " $1$"
    else
        cat
    fi
}
