#!/bin/bash
# built-with [CC]
# shows what compiler was used for packages installed on a Paludis-using system
#
# Copyright 2015, Kylie McClain <somasissounds@gmail.com>
# Distributed under the terms of the ISC License
#

set -eu -o pipefail
shopt -s failglob

pkgs=/var/db/paludis/repositories/installed/data/*/*

for pkg in $pkgs;do
    printf "%s/%s %s\n" $(<"$pkg/CATEGORY") $(echo "${pkg##*--}/*" | cut -d'/' -f1):$(echo "${pkg##*/}" | cut -d':' -f1 | cut -d'-' -f1) $(sed 's#.*/##g;s#.*-##g' "$pkg/CC");
done | {
    if [[ "$#" -gt 0 ]];then
        grep " $1$"
    else
        cat
    fi
}
