#!/bin/bash

pkgs=/var/db/paludis/repositories/installed/data/*/*

for pkg in $pkgs;do
    printf "%s/%s %s\n" $(<$pkg/CATEGORY) $(echo ${pkg##*--}/* | cut -d'/' -f1):$(echo "${pkg##*/}" | cut -d':' -f1 | cut -d'-' -f1) $(sed 's#.*/##g;s#.*-##g' $pkg/CC);
done
