#!/bin/bash
# clang-blacklist [pkg]
# add packages specified to the packages.gcc file used to blacklist clang usage
#
# Copyright 2015, Kylie McClain <somasissounds@gmail.com>
# Distributed under the terms of the ISC License
#

set -euf -o pipefail

packages_gcc="${packages_gcc:-$HOME/git/exheres/etc/clang-compat/packages.gcc}"

if [[ ! -f "$packages_gcc" ]];then
    echo "\"$packages_gcc\" doesn't exist"
    exit 1
fi

if [[ -z "$@" ]];then
    cat "$packages_gcc"
    exit 0
fi

temp=$(mktemp)

for pkg in $@;do
    if [[ "$pkg" != */* ]];then
        echo "\"$pkg\" isn't in the right format. category/pn, category/pn-pv, category/pn:slot, category/pn-pv:slot."
        exit 3
    fi
    echo "$pkg" >> "$packages_gcc" || exit 2
    sort -ud "$packages_gcc" > "$temp"
    yes | mv "$temp" "$packages_gcc" || :
    cd "$(dirname $packages_gcc)"
    if grep -q "$pkg" "$packages_gcc";then
        echo "\"$pkg\" already exists in packages.gcc."
    else
        git commit -m "clang-compat: add $pkg to packages.gcc" -v packages.gcc
    fi
done

rm -f "$temp" >/dev/null 2>&1
